server:
  servlet:
    context-path: /authorization-server
  port: 9080
spring:
  datasource:
    url: ${USERS_DB_URL:jdbc:h2:mem:transfers_users}
    username: ${USERS_DB_USER:root}
    password: ${USERS_DB_PWD:Password!}
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
  cache:
    type: redis
  redis:
    host: ${REDIS_CACHE_HOST:localhost}
    port: ${REDIS_CACHE_PORT:6379}
    timeout: ${REDIS_CACHE_TTL:900000}